name: Run tests on kedro-datasets

on:
  push:
    paths:
      - "kedro-datasets/**"
  pull_request:
    paths:
      - "kedro-datasets/**"
    types: [ synchronize ]

jobs:
  datasets-test:
    uses: ./.github/workflows/unit-test.yml
    with:
      plugin: kedro-datasets